create table Aisle
(
    ID int not null,
    Clothes_And_Misc text not null,
    Color text not null,
    Size text not null,
    Type_Of_Clothes text not null
);
--создает таблицу с Вещами/Цветом/Размером/Типов вещи(что хотите) НЕ ТРОГАТЬ

insert into Aisle
values
(1, 'Sweater', 'White', 'M', 'Turtleneck'),
    (2, 'Shirt', 'Grey', 'S', 'Turtleneck'),
    (3, 'Shirt', 'White', 'X', 'Turtleneck'),
    (4, 'Trousers', 'Black', 'M', 'Silk'),
    (5, 'Shorts', 'Blue', 'XL', 'Silk'),
    (6, 'Coat', 'Black', 'S', 'Leather'),
    (7, 'Jacket', 'Brown', 'XXL', 'Leather'),
    (8, 'Shirt', 'White', 'L', 'Hoodie'),
    (9, 'Cardigan', 'Black', 'L', 'Styrophome'),
    (10, 'Shirt', 'Red', 'S', 'Turtleneck'),
    (11, 'Jacket', 'Blue', 'X', 'Long Sleeves'),
    (12, 'Jeans', 'Grey', 'M', 'Torn'),
    (13, 'Sweater', 'Orange', 'L', 'Silk'),
    (14, 'Shirt', 'Red', 'L', 'Workout'),
    (15, 'Tank Top', 'Black', 'XL', 'Workout'),
    (16, 'T-Shirt', 'White', 'S', 'Crew neck'),
    (17, 'T-Shirt', 'Black', 'M', 'Crew neck'),
    (18, 'T-Shirt', 'Grey', 'XL', 'Crew neck'),
    (19, 'Jeans', 'Black', 'L', 'Baggy'),
    (20, 'Jeans', 'Black', 'S', 'Skinny'),
    (21, 'Denim shirt', 'Black', '2XL', 'Slim'),
    (22, 'Jumper', 'Navy', 'L', 'drop shoulder'),
    (23, 'Shirt', 'Navy', 'M', 'Hoodie'),
    (24, 'Jumper', 'Black', 'S', 'Knitted'),
    (25, 'SportsQilet', 'Blue', 'M', 'GoldenMoss'),
    (26, 'Trousers', 'Khaki', 'XL', 'Kargo'),
    (27, 'Jacket', 'Navy', 'XL', 'Bomber'),
    (28, 'Jacket', 'Black', 'S', 'Leather'),
    (29, 'Shorts', 'Khaki', 'M', 'Side taped'),
    (30, 'Jacket', 'Pink', 'L', 'OversizedZip'),
    (31, 'Jumper', 'Grey', 'S', 'Turtleneck'),
    (32, 'Jacket', 'Yellow', 'XL', 'Puffer'),
    (33, 'T-Shirt', 'White', 'L', 'Stripe'),
    (34, 'Shirt', 'Blue', 'S', 'Gingham'),
    (35, 'Jacket', 'Khaki', 'L', 'PufferWithHood'),
    (36, 'Jumper', 'Blue', 'XL', 'Oversized'),
    (37, 'Shirt', 'Midnight navy', 'S', 'Hoodie'),
    (38, 'Shirt', 'Khaki', 'L', 'Hoodie'),
    (39, 'Jacket', 'White', 'S', 'Puffer'),
    (40, 'Jumper', 'Dark grey', 'S', 'OversizedRibbed'),
    (41, 'Jumper', 'Black and White twist', 'L', 'RollNeck'),
    (42, 'Jacket', 'Light khaki', 'S', 'BomberWithSnapPockets'),
    (43, 'T-Shirt', 'White', 'XL', 'CrewNeck'),
    (44, 'Jacket', 'Black', 'S', 'HybridPuffer'),
    (45, 'Cardigan', 'Black', 'XL', 'KnittedHooded'),
    (46, 'Gilet', 'Light-grey', 'S', 'ThreadbareBorg'),
    (47, 'Jacket', 'Grey heather', 'L', 'Fleece'),
    (48, 'Jumper', 'Blue & Purple', 'XL', 'RollNeck'),
    (49, 'Jumper', 'Black', 'S', 'Turtleneck'),
    (50, 'Puffer gilet', 'Khaki', 'XL', 'ContrastPanel'),
    (51, 'Jeans', 'Wash blue', 'S', 'StraightLeg'),
    (52, 'Jacket', 'Black', 'M', 'LeatherRacer'),
    (53, 'Jumper', 'Light-grey', 'S', 'FishermanStripe'),
    (54, 'Polo', 'Black', 'M', 'LongSleeve'),
    (55, 'Jacket', 'Khaki', 'XL', 'Water repellent coach'),
    (56, 'Overcoat', 'Light-khaki', 'L', 'Oversized'),
    (57, 'Jacket', 'Black', 'XL', 'Windbreaker'),
    (58, 'Jumper', 'Black', 'S', 'Crew neck'),
    (59, 'Jumper', 'Lilac chalk', 'XL', 'Hoodie'),
    (60, 'Jumper', 'Grey', 'M', 'ditressed'),
    (61, 'Sweater', 'White', 'M', 'Turtleneck'),
    (62, 'Shirt', 'Grey', 'S', 'Turtleneck'),
    (63, 'Shirt', 'White', 'X', 'Turtleneck'),
    (64, 'Trousers', 'Black', 'M', 'Silk'),
    (65, 'Shorts', 'Blue', 'XL', 'Silk'),
    (66, 'Coat', 'Black', 'S', 'Leather'),
    (67, 'Jacket', 'Brown', 'XXL', 'Leather'),
    (68, 'Shirt', 'White', 'L', 'Hoodie'),
    (69, 'Cardigan', 'Black', 'L', 'Styrofoam'),
    (70, 'Shirt', 'Red', 'S', 'Turtleneck'),
    (71, 'Jacket', 'Blue', 'X', 'Long Sleeves'),
    (72, 'Jeans', 'Grey', 'M', 'Torn'),
    (73, 'Sweater', 'Orange', 'L', 'Silk'),
    (74, 'Shirt', 'Red', 'L', 'Workout'),
    (75, 'Tank Top', 'Black', 'XL', 'Workout'),
    (76, 'Skirt', 'Pink', 'M', 'Silk'),
    (77, 'Sweater', 'Navy blue', 'L', 'Cotton'),
    (78, 'Blazer', 'Blue', 'S', 'Long Sleeves'),
    (79, 'Coat', 'Red', 'XL', 'Wool'),
    (80, 'T-shirt', ' Black', 'M', 'Long Sleeves'),
    (81, 'Vest', 'Orange', 'X', 'Synthetic winterizer'),
    (82, 'Jumper', 'Green', 'S', ' Wool'),
    (83, 'Tank Top', 'Grey', 'XS', 'Plain'),
    (84, 'Jacket', 'Black', 'XL', 'Leather'),
    (85, 'Jeans', 'Blue', 'M', 'Denim'),
    (86, 'T-shirt', ' Black', 'L', ' Workout'),
    (87, 'Coat', 'Orange', 'S', 'Gabardine'),
    (88, 'Cloak', 'White', 'XL', 'Synthetic '),
    (89, 'Costume', 'Blue', 'M', 'Sport'),
    (90, 'Suit', 'Black', 'XL', 'Classic'),
    (91, 'Shirt', 'Red', 'X', 'Atlas'),
    (92, 'Trousers', 'Black', 'XXL', 'Bouffant'),
    (93, 'Sweater', 'Orange', 'S', 'Fleece'),
    (94, 'Robe', 'Yellow', 'XL', 'Cotton'),
    (95, 'Jumper', 'Brown', 'X', 'Fleece'),
    (96, 'Jumper', 'Black-Blue', 'X', 'Turtleneck'),
    (97, 'Sweater', 'White', 'L', 'Hoodie'),
    (98, 'Jeans', 'Black', 'M', 'Torn'),
    (99, 'Tights', 'Black', 'X', 'Cotton'),
    (100, 'Dress', 'Pink', 'XS', 'Cotton'),
    (101, 'Winbreaker', 'Red', 'XL', 'Synthetic winterizer'),
    (102, 'T-shirt', 'Red', 'XL', 'Long Sleeves'),
    (103, 'Vest', 'Yellow', 'M', 'Synthetic winterizer'),
    (104, 'Jumper', 'Black', 'L', ' Wool'),
    (105, 'Tank Top', 'Grey', 'S', 'Plain'),
    (106, 'Jacket', 'Black', 'XXL', 'Leather'),
    (107, 'Jeans', 'Black-Blue', 'L', 'Denim'),
    (108, 'T-shirt', ' Black', 'L', ' Workout'),
    (109, 'Coat', 'Brown', 'M', 'Gabardine'),
    (110, 'Cloak', 'Red', 'XXL', 'Synthetic '),
    (111, 'Costume', 'Black', 'XL', 'Sport'),
    (112, 'Suit', 'Black', 'M', 'Classic'),
    (113, 'Shirt', 'White', 'XL', 'Atlas'),
    (114, 'Trousers', 'Black', 'S', 'Bouffant'),
    (115, 'Sweater', 'Yellow', 'XS', 'Fleece'),
    (116, 'Robe', 'Red', 'X', 'Cotton'),
    (117, 'Jumper', 'Green', 'X', 'Cotton'),
    (118, 'Jumper', 'Black-Blue', 'X', 'Turtleneck'),
    (119, 'Sweater', 'Blue', 'XS', 'Hooded'),
    (120, 'Jeans', 'Black-Green', 'M', 'Torn'),
    (121, 'Tights', 'Grey', 'L', 'Cotton'),
    (122, 'Dress', 'Red', 'X', 'Cotton'),
    (123, 'Winbreaker', 'Grey', 'XXL', 'Synthetic winterizer'),
    (124, 'Tank Top', 'White', 'S', 'Bamboo'),
    (125, 'Cardigan', 'Blue', 'XL', 'Styrofoam'),
    (126, 'Skirt', 'Orange', 'L', 'Fleece'),
    (127, 'Coat', 'Grey', 'X', 'Wool'),
    (128, 'T-shirt', 'Black', 'L', ' Workout'),
    (129, 'Coat', 'White', 'S', 'Gabardine'),
    (130, 'Cloak', 'Blue', 'X', 'Synthetic '),
    (131, 'Costume', 'Blak-Green', 'XL', 'Sport'),
    (132, 'Suit', 'Black', 'L', 'Classic'),
    (133, 'Shirt', 'Grey', 'XL', 'Atlas'),
    (134, 'Trousers', 'Black', 'XL', 'Cotton'),
    (135, 'Sweater', 'Orange', 'S', 'Fleece'),
    (136, 'Robe', 'Green', 'X', 'Fleece'),
    (137, 'Jumper', 'Red', 'M', 'Cotton'),
    (138, 'Jumper', 'Black-Blue', 'X', 'Turtleneck'),
    (139, 'Sweater', 'White', 'L', 'Hooded'),
    (140, 'Jeans', 'Blue', 'M', 'Bouffant '),
    (141, 'Tights', 'Red', 'XL', 'Cotton'),
    (142, 'Blouse', 'Bright blue', 'X', 'Poplin'),
    (143, 'Shirt', 'Black', 'XL', 'Turtleneck'),
    (144, 'Breeches', 'Grey', 'XXL', 'Torn'),
    (145, 'Leggings', 'Black', 'L', 'Supplex'),
    (146, 'Jacket', 'Yellow', 'M', 'Long Sleeves'),
    (147, 'Tank Top', 'Black', 'XL', 'Workout'),
    (148, 'Skirt', 'Blue', 'S', 'Wool'),
    (149, 'Sweater', 'Navy blue', 'XL', 'Cotton'),
    (150, 'Blazer', 'Grey', 'S', 'Long Sleeves'),
    (151, 'Coat', 'Red', 'XL', 'Wool'),
    (152, 'T-shirt', ' Black', 'M', 'Long Sleeves'),
    (153, 'Vest', 'Green', 'XXL', 'Workout'),
    (154, 'Jumper', 'Red', 'XL', ' Cotton'),
    (155, 'Tank Top', 'Grey', 'M', 'Workout'),
    (156, 'Jacket', 'Orange', 'XS', 'Synthetic winterizer'),
    (157, 'Jeans', 'Blue', 'M', 'Denim'),
    (158, 'T-shirt', 'White', 'XS', ' Workout'),
    (159, 'Coat', 'Grey', 'XXL', 'Wool'),
    (160, 'Robe', 'Bright Red', 'L', 'Fleece'),
    (161, 'Coat', 'Blue', 'S', 'Wool'),
    (162, 'Jumper', 'Green', 'XL', 'Cotton'),
    (163, 'T-Shirt', 'White', 'XL', 'Oversize'),
    (164, 'Jeans',  'Black', 'M', 'Bouffant'),
    (165, 'Polo', 'White', 'M', 'Long Sleeves'),
    (166, 'Shirt', 'Black', 'L', 'Slim fit'),
    (167, 'Sweater', 'Red', 'M', 'Loose fit'),
    (168, 'Jacket', 'Green', 'S', 'Waterproof'),
    (169, 'Denim Jacket', 'Blue', 'XL', 'Regular fit'),
    (170, 'T-Shirt', 'Yellow', 'S', 'Cotton'),
    (171, 'Blouse', 'White', 'M', 'Chiffon material'),
    (172, 'Leather jacket', 'Black', 'L', 'Bomber'),
    (173, 'Skirt', 'Red', 'XS', 'Pencil style'),
    (174, 'Pants', 'Green', 'L', 'Cargo style'),
    (175, 'Shorts', 'Blue', 'M', 'Swim material'),
    (176, 'Subdress', 'Yellow', 'S', 'Maxi style'),
    (177, 'Blouse', 'White', 'XS', 'Peasant style'),
    (178, 'Shirt', 'Blue', 'S', 'Denim'),
    (179, 'Dress', 'Red', 'M', 'Bodycon'),
    (180, 'Skirt', 'Green', 'L', 'Midi length'),
    (181, 'Jeans', 'Black', 'XL', 'Skinny fit'),
    (182, 'Jacket', 'Brown', 'XXL', 'Leather'),
    (183, 'Pants', 'Purple', 'S', 'Wide leg'),
    (184, 'Sweater', 'Gray', 'M', 'Cable knit'),
    (185, 'T-shirt', 'Yellow', 'L', 'Graphic print'),
    (186, 'Hoodie', 'Orange', 'XL', 'Zip up'),
    (187, 'Sunglasses', 'Pink', 'One size', 'Aviator'),
    (188, 'Bag', 'Maroon', 'Medium', 'Tote'),
    (189, 'Scarf', 'Turquoise', 'One size', 'Oversized'),
    (190, 'Hat', 'Navy', 'One size', 'Baseball cap'),
    (191, 'Shoes', 'Beige', '7', 'Sneakers'),
    (192, 'Boots', 'Olive', '8', 'Ankle boots'),
    (193, 'Flats', 'Burgundy', '9', 'Ballet'),
    (194, 'Heels', 'Gold', '10', 'Stiletto'),
    (195, 'Sandal', 'Silver', '11', 'Flat sandals'),
    (196, 'Slippers', 'Bronze', '12', 'Fuzzy'),
    (197, 'Leggings', 'Turquoise', 'M', 'High waisted'),
    (198, 'Joggers', 'Pink', 'L', 'Camo print'),
    (199, 'Shorts', 'Green', 'XL', 'Biker shorts'),
    (200, 'Rompers', 'Yellow', 'S', 'Off the shoulder');



--здесь все добавляете
--добавляет в пустую таблицу хар-ки как Вещь - свитер/Цвет - Белый/Размер - М/Тип - с воротником (последовательность важна)
--кстати нужно таблицу удалять каждый раз когда хотите новые данные внести после того как запустили прогу, тк старые данные наложятся на новые и будут копии (database > postgres@localhost > postgres > public > tables > удалите Aisle и запустите эту и первую функцию)
--если закончили в конце вместо запятой поставить ;

select * from Aisle;
--выводит в строку всю таблицу

select color, Type_Of_Clothes from Aisle;
--выводит определенный столбец, НЕ СТРОКУ (может сколько угодно столбцов вывести)

select * from Aisle where Type_Of_Clothes = 'Turtleneck';
--выводит опр строки с "Turtleneck"








